/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bankV4Sol from "./BankV4.sol";
export type { bankV4Sol };
export type { BankV1 } from "./BankV1";
export type { BankV2 } from "./BankV2";
export type { BankV3 } from "./BankV3";
