/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bankV7Sol from "./BankV7.sol";
export type { bankV7Sol };
export type { BankV1 } from "./BankV1";
export type { BankV2 } from "./BankV2";
export type { BankV3 } from "./BankV3";
export type { BankV4 } from "./BankV4";
export type { BankV5 } from "./BankV5";
export type { BankV5BETA } from "./BankV5BETA";
export type { BankV6 } from "./BankV6";
