/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BankV5__factory } from "./BankV5__factory";
export { BankV5BETA__factory } from "./BankV5BETA__factory";
