/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as bankV5Sol from "./BankV5.sol";
export * as bankV5BetaSol from "./BankV5BETA.sol";
export { BankV1__factory } from "./BankV1__factory";
export { BankV2__factory } from "./BankV2__factory";
export { BankV3__factory } from "./BankV3__factory";
export { BankV4__factory } from "./BankV4__factory";
