/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BankV1__factory } from "./BankV1__factory";
export { BankV2__factory } from "./BankV2__factory";
export { BankV3__factory } from "./BankV3__factory";
export { BankV4__factory } from "./BankV4__factory";
export { BankV5__factory } from "./BankV5__factory";
export { BankV5BETA__factory } from "./BankV5BETA__factory";
export { BankV6__factory } from "./BankV6__factory";
