/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface BankV7Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "addLiquidityPOL"
      | "addLiquidityToken"
      | "approveAccount"
      | "balance"
      | "blockAccount"
      | "breakContract"
      | "buyToken"
      | "deposit"
      | "feeExchange"
      | "getAccountBalance"
      | "getStockTokens"
      | "getWithdrawFee"
      | "getWithdrawFeeCollected"
      | "initialize"
      | "initializeV2"
      | "initializeV3"
      | "isBlocked"
      | "isPaused"
      | "isWhitelisted"
      | "liquidityPOL"
      | "owner"
      | "proxiableUUID"
      | "registerRequest"
      | "removeLiquidityPOL"
      | "removeLiquidityToken"
      | "renounceOwnership"
      | "sellToken"
      | "tokenExchange"
      | "totalWithdrawFeeCollected"
      | "transferOwnership"
      | "unBreakContract"
      | "updateFeeExchange"
      | "updateTokenExchange"
      | "updateWithdrawFee"
      | "upgradeToAndCall"
      | "withdraw"
      | "withdrawFee"
      | "withdrawFeeAdmin"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DepositMade"
      | "FeeExchangeUpdated"
      | "Initialized"
      | "LiquidityPolAdd"
      | "LiquidityTokenAdd"
      | "OwnershipTransferred"
      | "Paused"
      | "TokenBuy"
      | "TokenSell"
      | "Unpaused"
      | "Upgraded"
      | "WithdrawFeeUpdated"
      | "WithdrawMade"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidityPOL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidityToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blockAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "breakContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "buyToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeExchange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStockTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawFeeCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeV2",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeV3",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isBlocked",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isWhitelisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidityPOL",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerRequest",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidityPOL",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidityToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenExchange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalWithdrawFeeCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unBreakContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateFeeExchange",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTokenExchange",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWithdrawFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFeeAdmin",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidityPOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidityToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blockAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "breakContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeExchange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStockTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawFeeCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeV3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isBlocked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidityPOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidityPOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidityToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenExchange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalWithdrawFeeCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unBreakContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFeeExchange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTokenExchange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWithdrawFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFeeAdmin",
    data: BytesLike
  ): Result;
}

export namespace DepositMadeEvent {
  export type InputTuple = [user: AddressLike, cashValue: BigNumberish];
  export type OutputTuple = [user: string, cashValue: bigint];
  export interface OutputObject {
    user: string;
    cashValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeExchangeUpdatedEvent {
  export type InputTuple = [newFeeExchange: BigNumberish];
  export type OutputTuple = [newFeeExchange: bigint];
  export interface OutputObject {
    newFeeExchange: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityPolAddEvent {
  export type InputTuple = [value: BigNumberish];
  export type OutputTuple = [value: bigint];
  export interface OutputObject {
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityTokenAddEvent {
  export type InputTuple = [value: BigNumberish];
  export type OutputTuple = [value: bigint];
  export interface OutputObject {
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenBuyEvent {
  export type InputTuple = [
    client: AddressLike,
    polOutGoing: BigNumberish,
    tokensReceived: BigNumberish
  ];
  export type OutputTuple = [
    client: string,
    polOutGoing: bigint,
    tokensReceived: bigint
  ];
  export interface OutputObject {
    client: string;
    polOutGoing: bigint;
    tokensReceived: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenSellEvent {
  export type InputTuple = [
    client: AddressLike,
    tokensOutGoing: BigNumberish,
    polReceived: BigNumberish
  ];
  export type OutputTuple = [
    client: string,
    tokensOutGoing: bigint,
    polReceived: bigint
  ];
  export interface OutputObject {
    client: string;
    tokensOutGoing: bigint;
    polReceived: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawFeeUpdatedEvent {
  export type InputTuple = [newWithdrawFee: BigNumberish];
  export type OutputTuple = [newWithdrawFee: bigint];
  export interface OutputObject {
    newWithdrawFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawMadeEvent {
  export type InputTuple = [user: AddressLike, cashValue: BigNumberish];
  export type OutputTuple = [user: string, cashValue: bigint];
  export interface OutputObject {
    user: string;
    cashValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BankV7 extends BaseContract {
  connect(runner?: ContractRunner | null): BankV7;
  waitForDeployment(): Promise<this>;

  interface: BankV7Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  addLiquidityPOL: TypedContractMethod<[], [void], "payable">;

  addLiquidityToken: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  approveAccount: TypedContractMethod<
    [_account: AddressLike],
    [void],
    "nonpayable"
  >;

  balance: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  blockAccount: TypedContractMethod<
    [_account: AddressLike],
    [void],
    "nonpayable"
  >;

  breakContract: TypedContractMethod<[], [void], "nonpayable">;

  buyToken: TypedContractMethod<[], [void], "payable">;

  deposit: TypedContractMethod<[], [void], "payable">;

  feeExchange: TypedContractMethod<[], [bigint], "view">;

  getAccountBalance: TypedContractMethod<
    [_account: AddressLike],
    [bigint],
    "view"
  >;

  getStockTokens: TypedContractMethod<[], [bigint], "view">;

  getWithdrawFee: TypedContractMethod<[], [bigint], "view">;

  getWithdrawFeeCollected: TypedContractMethod<[], [bigint], "view">;

  initialize: TypedContractMethod<
    [initialOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  initializeV2: TypedContractMethod<
    [_taxaInicial: BigNumberish],
    [void],
    "nonpayable"
  >;

  initializeV3: TypedContractMethod<[], [void], "nonpayable">;

  isBlocked: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isPaused: TypedContractMethod<[], [boolean], "view">;

  isWhitelisted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  liquidityPOL: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  registerRequest: TypedContractMethod<
    [_name: string, _age: BigNumberish, _country: string],
    [void],
    "nonpayable"
  >;

  removeLiquidityPOL: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeLiquidityToken: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sellToken: TypedContractMethod<
    [_amountTokens: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokenExchange: TypedContractMethod<[], [string], "view">;

  totalWithdrawFeeCollected: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unBreakContract: TypedContractMethod<[], [void], "nonpayable">;

  updateFeeExchange: TypedContractMethod<
    [_newFeeExchange: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateTokenExchange: TypedContractMethod<
    [_newTokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  updateWithdrawFee: TypedContractMethod<
    [_newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  withdraw: TypedContractMethod<
    [_valueRequested: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawFee: TypedContractMethod<[], [bigint], "view">;

  withdrawFeeAdmin: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addLiquidityPOL"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "addLiquidityToken"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveAccount"
  ): TypedContractMethod<[_account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "balance"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "blockAccount"
  ): TypedContractMethod<[_account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "breakContract"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "buyToken"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "feeExchange"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAccountBalance"
  ): TypedContractMethod<[_account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStockTokens"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWithdrawFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWithdrawFeeCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[initialOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initializeV2"
  ): TypedContractMethod<[_taxaInicial: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initializeV3"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isBlocked"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWhitelisted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "liquidityPOL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerRequest"
  ): TypedContractMethod<
    [_name: string, _age: BigNumberish, _country: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeLiquidityPOL"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeLiquidityToken"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sellToken"
  ): TypedContractMethod<[_amountTokens: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenExchange"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalWithdrawFeeCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unBreakContract"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateFeeExchange"
  ): TypedContractMethod<[_newFeeExchange: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTokenExchange"
  ): TypedContractMethod<[_newTokenAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateWithdrawFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[_valueRequested: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawFeeAdmin"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "DepositMade"
  ): TypedContractEvent<
    DepositMadeEvent.InputTuple,
    DepositMadeEvent.OutputTuple,
    DepositMadeEvent.OutputObject
  >;
  getEvent(
    key: "FeeExchangeUpdated"
  ): TypedContractEvent<
    FeeExchangeUpdatedEvent.InputTuple,
    FeeExchangeUpdatedEvent.OutputTuple,
    FeeExchangeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityPolAdd"
  ): TypedContractEvent<
    LiquidityPolAddEvent.InputTuple,
    LiquidityPolAddEvent.OutputTuple,
    LiquidityPolAddEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityTokenAdd"
  ): TypedContractEvent<
    LiquidityTokenAddEvent.InputTuple,
    LiquidityTokenAddEvent.OutputTuple,
    LiquidityTokenAddEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "TokenBuy"
  ): TypedContractEvent<
    TokenBuyEvent.InputTuple,
    TokenBuyEvent.OutputTuple,
    TokenBuyEvent.OutputObject
  >;
  getEvent(
    key: "TokenSell"
  ): TypedContractEvent<
    TokenSellEvent.InputTuple,
    TokenSellEvent.OutputTuple,
    TokenSellEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawFeeUpdated"
  ): TypedContractEvent<
    WithdrawFeeUpdatedEvent.InputTuple,
    WithdrawFeeUpdatedEvent.OutputTuple,
    WithdrawFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawMade"
  ): TypedContractEvent<
    WithdrawMadeEvent.InputTuple,
    WithdrawMadeEvent.OutputTuple,
    WithdrawMadeEvent.OutputObject
  >;

  filters: {
    "DepositMade(address,uint256)": TypedContractEvent<
      DepositMadeEvent.InputTuple,
      DepositMadeEvent.OutputTuple,
      DepositMadeEvent.OutputObject
    >;
    DepositMade: TypedContractEvent<
      DepositMadeEvent.InputTuple,
      DepositMadeEvent.OutputTuple,
      DepositMadeEvent.OutputObject
    >;

    "FeeExchangeUpdated(uint256)": TypedContractEvent<
      FeeExchangeUpdatedEvent.InputTuple,
      FeeExchangeUpdatedEvent.OutputTuple,
      FeeExchangeUpdatedEvent.OutputObject
    >;
    FeeExchangeUpdated: TypedContractEvent<
      FeeExchangeUpdatedEvent.InputTuple,
      FeeExchangeUpdatedEvent.OutputTuple,
      FeeExchangeUpdatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "LiquidityPolAdd(uint256)": TypedContractEvent<
      LiquidityPolAddEvent.InputTuple,
      LiquidityPolAddEvent.OutputTuple,
      LiquidityPolAddEvent.OutputObject
    >;
    LiquidityPolAdd: TypedContractEvent<
      LiquidityPolAddEvent.InputTuple,
      LiquidityPolAddEvent.OutputTuple,
      LiquidityPolAddEvent.OutputObject
    >;

    "LiquidityTokenAdd(uint256)": TypedContractEvent<
      LiquidityTokenAddEvent.InputTuple,
      LiquidityTokenAddEvent.OutputTuple,
      LiquidityTokenAddEvent.OutputObject
    >;
    LiquidityTokenAdd: TypedContractEvent<
      LiquidityTokenAddEvent.InputTuple,
      LiquidityTokenAddEvent.OutputTuple,
      LiquidityTokenAddEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "TokenBuy(address,uint256,uint256)": TypedContractEvent<
      TokenBuyEvent.InputTuple,
      TokenBuyEvent.OutputTuple,
      TokenBuyEvent.OutputObject
    >;
    TokenBuy: TypedContractEvent<
      TokenBuyEvent.InputTuple,
      TokenBuyEvent.OutputTuple,
      TokenBuyEvent.OutputObject
    >;

    "TokenSell(address,uint256,uint256)": TypedContractEvent<
      TokenSellEvent.InputTuple,
      TokenSellEvent.OutputTuple,
      TokenSellEvent.OutputObject
    >;
    TokenSell: TypedContractEvent<
      TokenSellEvent.InputTuple,
      TokenSellEvent.OutputTuple,
      TokenSellEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "WithdrawFeeUpdated(uint256)": TypedContractEvent<
      WithdrawFeeUpdatedEvent.InputTuple,
      WithdrawFeeUpdatedEvent.OutputTuple,
      WithdrawFeeUpdatedEvent.OutputObject
    >;
    WithdrawFeeUpdated: TypedContractEvent<
      WithdrawFeeUpdatedEvent.InputTuple,
      WithdrawFeeUpdatedEvent.OutputTuple,
      WithdrawFeeUpdatedEvent.OutputObject
    >;

    "WithdrawMade(address,uint256)": TypedContractEvent<
      WithdrawMadeEvent.InputTuple,
      WithdrawMadeEvent.OutputTuple,
      WithdrawMadeEvent.OutputObject
    >;
    WithdrawMade: TypedContractEvent<
      WithdrawMadeEvent.InputTuple,
      WithdrawMadeEvent.OutputTuple,
      WithdrawMadeEvent.OutputObject
    >;
  };
}
